DATA_DIRECTORY: /storage/user/dendorfp/
DT: 0.4
MAX_AGE: 179
MAX_AGE_VIS: 30
Y0: 600
REID_METRIC: "L2_APP_IOU"
CLEAN-POSITIONS: True 
HOMOGRAPHY: "homography_depth"
L2_THRESHOLD: 2.5  
IOU_THRESHOLD: 0.25
MIN_IOU_THRESHOLD: 0.2
APP_THRESHOLD: 1.8
NR_PREDICTIONS: 3
PRED_MODEL: "mggan"

