DATA_DIRECTORY: ./data
DT: 0.4
MAX_AGE: 179
MAX_AGE_VIS: 30
Y0: 600
REID_METRIC: "L2_APP_IOU"
CLEAN-POSITIONS: True 
HOMOGRAPHY: "homography_depth"
L2_THRESHOLD: 2.5  
IOU_THRESHOLD: 0.25
MIN_IOU_THRESHOLD: 0.2
APP_THRESHOLD: 1.8
NR_PREDICTIONS: 3
PRED_MODEL: "mggan"
DEVICE: "cpu"
MGGAN_WEIGHTS: "/Users/patrickdendorfer/phd/paper/QuoVadis/data/predictor_weights/mggan-3gen"
MGGAN_LOG_DIR: "/Users/patrickdendorfer/phd/paper/QuoVadis/src/trajectory_predictor/logs"
